# helper function
function include {
    [[ -s "$1" ]] && source "$1" || echo "$1 not found"
} 

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Theme
ZSH_THEME=powerlevel10k/powerlevel10k

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status time)
POWERLEVEL9K_CONTEXT_TEMPLATE="%m"

# Dir segment
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"

# Vcs segment aka git
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

plugins=(
  git
  bundler
  dotenv
  osx
  rake
  rbenv
  ruby
)

# functions and aliases
include $HOME/.zsh/functions.zsh
include $HOME/.zsh/aliases.zsh
#include $HOME/.zsh/zgen-setup.zsh

source $ZSH/oh-my-zsh.sh